[[main]]
  name = "announcements"
  pageRef = "announcements"
  weight = 10

[[main]]
  name = "skill of the week"
  pageRef = "skill-of-the-week"
  weight = 20

[[main]]
  name = "boss of the week"
  url = "boss-of-the-week"
  weight = 30


[[footer]]
  name = "Made with love by Dad Pvmer"
  url = "https://cyberwizardlabs.com"