[[main]]
  name = "discord"
  url = "discord.gg/crypticvoiders"
  
[[main]]
  name = "announcements"
  pageRef = "announcements"
  weight = 20

[[main]]
  name = "skill of the week"
  url = "skill-of-the-week"
  weight = 30

[[main]]
  name = "boss of the week"
  url = "boss-of-the-week"
  weight = 40



[[footer]]
  name = "Made with love by Dad Pvmer"
  url = "https://cyberwizardlabs.com"