baseURL = 'https://crypticvoid.com/'
languageCode = 'en-us'
title = 'Cryptic Void'
theme = 'glim-midnight'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
    title = "Cryptic Void"
    phrases = ["Community", "Fun", "Old School Runescape"]
    links = [
    {name = "Discord", url = "https://discord.gg/crypticvoiders"},    
    {name = "Announcements", url = "/announcements"}
] 
    backgroundVideo = "bg.mp4"
    footer = "Made with ❤️ by <a href='https://mansoorbarri.com/' target='_blank'>Mansoor Barri</a>"
