baseURL = 'https://crypticvoid.com/'
languageCode = 'en-us'
title = 'Cryptic Void'
theme = 'glim-midnight'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
    title = "Cryptic Void"
    phrases = ["Community", "Fun", "Old School Runescape"]
    links = [
    {name = "Discord", url = "https://discord.gg/crypticvoiders"},    
    {name = "Announcements", url = "/announcements"},
    {name = "Skill of the Week", url ="/skill-of-the-week"},	
    {name = "Boss of the Week", url="/Boss-of-the-week"}
] 
    backgroundVideo = "bg.mp4"
    footer = "Made with ❤️ by <a href='https://cyberwizardlabs.com' target='_blank'>Dad Pvmer</a>"
